<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class AccountRecord extends TActiveRecord 
{       
	const TABLE='account';

	public $acc_id;
	public $name;
	public $family;
	public $sex;
	public $username;
	public $password;
	public $last_login;
	public $status;
	public $_del;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->name;
	}
}