<?php
/**
 * Auto generated by PRADO - WSAT on 2019-04-28 10:36:26.
 * @author -MOHAMMAD-$               
 */
class AdminRecord extends TActiveRecord 
{       
	const TABLE='Admin';

	public $u_id;
	public $a_id;
	public $name;
	public $family;
	public $sex;
	public $username;
	public $password;
	public $last_login;
	public $status;
	public $national_code;
	public $pic_path;
	public $j_id;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'report' => array(self::HAS_MANY, 'ReportRecord', 'u_id')
	);
                
	public function __toString() {
		return $this->name;
	}
	public function getFamily(){
		$admin = AdminRecord::finder()->find("u_id = ?",$this->u_id);
		if($admin instanceof UserRecord)
		{
			return $admin->family;
		}
	}
	public function getName(){
		$admin = AdminRecord::finder()->find("u_id = ?",$this->u_id);
		if($admin instanceof UserRecord)
		{
			if($admin->sex == 1)
				return "آقای - " . $admin->name;
			else if($admin->sex == 2)
				return "خانم - " . $admin->name;
			else if($admin->sex == 0)
				return $admin->name;
		}
	}
	public function getCode(){
		$admin = AdminRecord::finder()->find("u_id = ?",$this->u_id);
		if($admin instanceof UserRecord)
		{
			return $admin->national_code;
		}
	}
	public function getImage(){ 
		$admin = AdminRecord::finder()->find("u_id = ?",$this->u_id);
		if($admin instanceof UserRecord)
		{
			return $admin->pic_path;
		} 
	}
	public function getJob(){
		$account = AdminRecord::finder()->find("u_id = ? ",$this->u_id);
		if($account instanceof UserRecord){
			$job = JobRecord::finder()->find("j_id = ?",$account->j_id);
			if($job instanceof JobRecord)
			{
				return $job->name;
			}
		}
	}
}