<?php
/**
 * Auto generated by PRADO - WSAT on 2020-08-04 12:30:57.
 * @author                
 */
class BooksRecord extends TActiveRecord 
{       
	const TABLE='books';

	public $book_id;
	public $name;
	public $price;
	public $desc;
	public $sub_cat;
	public $pic_path;
	public $pic_path1;
	public $pic_path2;
	public $pic_path3;
	public $c_id;
	public $goodreads_rating;
	public $status;
	public $_del;
	public $u_id;
	public $publisher_id;
	public $pic_path4;
	public $publisher_year;
	public $shabak;
	public $cover;
	public $language;
	public $page;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'book_authors' => array(self::HAS_MANY, 'BookAuthorsRecord', 'book_id'),
		'book_translator' => array(self::HAS_MANY, 'BookTranslatorRecord', 'book_id'),
		'sub_cat' => array(self::BELONGS_TO, 'SubCatRecord', 'sub_cat'),
		'user' => array(self::BELONGS_TO, 'UserRecord', 'u_id'),
		'cat' => array(self::BELONGS_TO, 'CatRecord', 'c_id'),
		'order1' => array(self::HAS_MANY, 'Order1Record', 'book_id')
	);
                
	public function __toString() {
		return $this->name;
	}

	public function pic_path()
	{
		$book = BooksRecord::finder()->find("book_id = ?",$this->book_id);
		if($book instanceof BooksRecord)
		{
			return $book->pic_path;
		}
	}

	public function getCat()
	{
		$book = BooksRecord::finder()->find("book_id = ?",$this->book_id);
		if($book instanceof BooksRecord)
		{
			$cat = CatRecord::finder()->find("c_id = ?",$book->c_id);
			if($cat instanceof CatRecord)
			{
				return $cat->name;
			}
		}
	}
	public function name()
	{
		$book = BooksRecord::finder()->find("book_id = ?",$this->book_id);
		if($book instanceof BooksRecord)
		{
			return $book->name;
		}
	}
	public function desc()
	{
		$book = BooksRecord::finder()->find("book_id = ?",$this->book_id);
		if($book instanceof BooksRecord)
		{
			return $book->desc;
		}
	}

	public function publisher_name()
	{
		$publisher = PublisherRecord::finder()->find("publisher_id = ?",$this->publisher_id);
		if($publisher instanceof PublisherRecord)
		{
			return $publisher->publisher_name;
		}
	}
	public function getPrice()
	{
		$book = BooksRecord::finder()->find("book_id = ?",$this->book_id);
		if($book instanceof BooksRecord)
		{
			return number_format($book->price);
			
		}
	}

}