<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class CatRecord extends TActiveRecord 
{       
	const TABLE='cat';

	public $c_id;
	public $name;
	public $status;
	public $pic;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'books' => array(self::HAS_MANY, 'BooksRecord', 'cat'),
		'sub_cat' => array(self::HAS_MANY, 'SubCatRecord', 'c_id')
	);
                
	public function __toString() {
		return $this->name;
	}

	public function getStatus(){
		if($this->status == 0)
			return "تعیین نشده";
		if($this->status == 1)
			return "فعال";
		if($this->status == 2)
			return "غیر فعال";
	}
}