<?php
/**
 * Auto generated by PRADO - WSAT on 2020-03-23 11:33:02.
 * @author MOHAMMAD$               
 */
class EventRecord extends TActiveRecord 
{       
	const TABLE='event';

	public $e_id;
	public $title;
        public $number;
	public $text;
	public $pic_path;
	public $date;
	public $status;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->title;
	}
}
