<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class HomeSettingRecord extends TActiveRecord 
{       
	const TABLE='home_setting';

	public $hset_id;
	public $name;
	public $value;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->name;
	}
}