<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class LimitationRecord extends TActiveRecord 
{       
	const TABLE='limitation';

	public $lim_id;
	public $u_id;
	public $_new_user;
	public $_users_list;
	public $_new_order;
	public $_orders_list;
	public $_new_product;
	public $_products_list;
	public $_manage_reports;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'user' => array(self::BELONGS_TO, 'UserRecord', 'u_id')
	);
                
	public function __toString() {
		return $this->lim_id;
	}
}