<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class PublisherRecord extends TActiveRecord 
{       
	const TABLE='publisher';

	public $publisher_id;
	public $publisher_name;
	public $_del;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'books' => array(self::HAS_MANY, 'BooksRecord', 'publisher_id')
	);
                
	public function __toString() {
		return $this->publisher_name;
	}
}