<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class QuoteRecord extends TActiveRecord 
{       
	const TABLE='quote';

	public $quote_id;
	public $quote;
	public $author_id;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'user' => array(self::BELONGS_TO, 'UserRecord', 'u_id')
	);
                
	public function __toString() {
		return $this->name;
	}

	public function getAuthor()
	{
		$author = AuthorsRecord::finder()->find("author_id = ?",$this->author_id);
		if($author instanceof AuthorsRecord)
		{
            return $author->name;
		} 
	}
	// public function getId()
	// {
	// 	$user = UserRecord::finder()->find("u_id = ?",$this->u_id);
	// 	if($user instanceof UserRecord)
	// 	{
    //         return $user->u_id;
	// 	} 
	// }
	// public function getComment()
	// {
	// 	return substr($this->message,0,3);
	// }
}