<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class SubCatRecord extends TActiveRecord 
{       
	const TABLE='sub_cat';

	public $sc_id;
	public $name;
	public $status;
	public $c_id;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'books' => array(self::HAS_MANY, 'BooksRecord', 'sub_cat'),
		'cat' => array(self::BELONGS_TO, 'CatRecord', 'c_id')
	);
                
	public function __toString() {
		return $this->name;
	}
}