<?php
/**
 * Auto generated by PRADO - WSAT on 2020-03-23 11:33:02.
 * @author MOHAMMAD$               
 */
class TicketRecord extends TActiveRecord 
{       
	const TABLE='ticket';

	public $tick_id;
	public $text;
	public $answer;
	public $date;
	public $sender;
	public $receiver;
	public $title;
	public $status;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->tick_id;
	}
}