<?php
/**
 * Auto generated by PRADO - WSAT on 2020-03-23 11:33:02.
 * @author MOHAMMAD$               
 */
class TourRecord extends TActiveRecord 
{       
	const TABLE='tour';

	public $t_id;
	public $number;
	public $title; 
	public $pic1;
	public $pic2;
	public $pic3;
	public $pic4;
	public $pic5;
	public $name1;
	public $name2;
	public $name3;
	public $name4;
	public $name5;
	public $start_date;
	public $end_date;
	public $tour_type;
	public $level;
	public $location;
	public $service;
	public $desc;
	public $equipments;
	public $costs;	
	public $link;
	public $status;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->title;
	}
}
