<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class TranslatorRecord extends TActiveRecord 
{       
	const TABLE='translator';

	public $translator_id;
	public $name;
	public $_del;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->name;
	}
}