<?php
/**
 * Auto generated by PRADO - WSAT on 2020-07-20 11:28:17.
 * @author                
 */
class UserRecord extends TActiveRecord 
{       
	const TABLE='user';

	public $u_id;
	public $name;
	public $family;
	public $mobile;
	public $password;
	public $email;
	public $status;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS = array (
		'address' => array(self::HAS_MANY, 'AddressRecord', 'u_id'),
		'books' => array(self::HAS_MANY, 'BooksRecord', 'u_id'),
		'like' => array(self::HAS_MANY, 'LikeRecord', 'u_id'),
		'limitation' => array(self::HAS_MANY, 'LimitationRecord', 'u_id'),
		'order1' => array(self::HAS_MANY, 'Order1Record', 'u_id')
	);
                
	public function __toString() {
		return $this->name;
	}
}